name: Test
on: [workflow_call]

permissions:
  id-token: write
  contents: read

jobs:
  terratest:
    runs-on: ubuntu-latest
    env:
      TFE_TOKEN: ${{ secrets.TFE_SECURITY_READ_TOKEN }} 
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::217938946443:role/gh-action-read-only
        role-session-name: terraformModuleTest
        role-duration-seconds: 1200
    
    - uses: actions/checkout@v3
    - name: test
      working-directory: ./test
      run: go test -short ./...