name: Publish

on: [workflow_call]

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version
        id: read-version
        run: echo "version=$(cat version)" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        id: create-release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: "${{ steps.read-version.outputs.version }}",
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: "${{ steps.read-version.outputs.version }}"
              });
              return {
                id: response.data.id,
                upload_url: response.data.upload_url
              }
            } catch (error) {
              core.setFailed(error.message);
            }
